version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: crystalgym_postgres
    # restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simondileo
      POSTGRES_DB: crystalgym_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
